image:
  repository: divvycloud/divvycloud
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

storage:
    storageClass: rook-block
    size: 10Gi

ingress:
  enabled: true
  annotations: {}
  kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    -  test.divvycloud.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
