apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-harvester
  labels:
    app: {{ template "divvycloud.name" . }}-harvester
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}

spec:
  replicas: {{ if .Values.replicaCounts  }}  {{ .Values.replicaCounts.harvesters | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-harvester
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-harvester
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{ if .Values.enablePlugins }}
          command: ['unzip','/tmpPlugins/plugins.zip','/plugins/',';']
          {{ end }}
          args: ['divvycloudworker','-t','harvester','-n']
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          {{ if .Values.enablePlugins }}
          volumeMounts:
          - name: plugins
            mountPath: /tmpPlugins/
            readOnly: true
          {{ end }}
      {{if .Vales.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      {{ if .Values.enablePlugins }}
      volumes:
      - name: plugins
        secret:
            secretName: divvycloud-plugins
      {{ end }}
