apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-interfaceserver
  labels:
    app: {{ template "divvycloud.name" . }}-interfaceserver
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ if .Values.replicaCounts  }}  {{ .Values.replicaCounts.interfaceservers | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-interfaceserver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-interfaceserver
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: ['divvyinterfaceserver','-n']
          livenessProbe:
            httpGet:
              path: /Status
              port: 8001
          readinessProbe:
            httpGet:
              path: /Status
              port: 8001
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          {{ if .Values.enablePlugins }}
          volumeMounts:
          - name: plugins
            mountPath: /plugins/
            readOnly: true
          {{ end }}
      {{if .Vales.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      {{ if .Values.enablePlugins }}
      volumes:
      - name: plugins
        configMap:
            name: {{ template "divvycloud.name" . }}-plugins
      {{ end }}
