apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-longharvest
  labels:
    app: {{ template "divvycloud.name" . }}-longharvest
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
spec:
  replicas: {{ if .Values.replicaCounts  }}  {{ .Values.replicaCounts.longharvesters | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-longharvest
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-longharvest
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{ if eq .Values.enablePlugins true }}
          command: ['sh','/scripts/entrypoint.sh']
          {{ end }}
          args: ['divvycloudworker','-t','harvester-long','-n']
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          volumeMounts:
          - name: entrypoint
            mountPath: /scripts/
          {{ if eq .Values.enablePlugins true }}
          - name: plugins
            mountPath: /tmpPlugins/
            readOnly: true
          {{ end }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      volumes:
      {{ if eq .Values.enablePlugins true }}
      - name: plugins
        secret:
            secretName: divvycloud-plugins
      {{ end }}
      - name: entrypoint
        secret:
            secretName: {{ template "divvycloud.name" . }}-entrypoint
