apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-longharvest
  labels:
    app: {{ template "divvycloud.name" . }}-longharvest
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ if .Values.longharvest  }}  {{ .Values.longharvest.replicaCount | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-longharvest
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-longharvest
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.imageName }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: ['divvycloudworker','-t','harvester-long','-n']
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
