
{{- if .Values.database_host -}} 
{{- else -}}
{{ if .Values.storage }} 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name | default "divvycloud-mysql-pvc" }}
  labels:
    app: mysql
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "30Gi" }}
{{ end  }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "divvycloud.name" . }}-mysql
  labels:
    app: {{ template "divvycloud.name" . }}-mysql
    chart: {{ template "divvycloud.chart" . }}-mysql
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: {{ template "divvycloud.name" . }}-mysql
    release: {{ .Release.Name }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-mysql
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-mysql
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: divvycloud/quickstart-db
        args:
          - "--ignore-db-dir=lost+found --datadir=/var/lib/mysq/data"
        name: {{ template "divvycloud.name" . }}-mysql
        envFrom:
          - secretRef:
              name: {{ template "divvycloud.name" . }}-secret           
        ports:
        - containerPort: 3306
    {{ if .Values.storage }}
        volumeMounts:
        - name: {{ .Values.storage.name | default "divvycloud-mysql-pvc" }}
          mountPath: /var/lib/mysql
          subPath: data
      volumes: 
      - name: {{ .Values.storage.name | default "divvycloud-mysql-pvc" }}
    {{ end }}

{{- end -}}



