apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-processor
  labels:
    app: {{ template "divvycloud.name" . }}-processor
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
spec:
  replicas: {{ if .Values.replicaCounts  }}  {{ .Values.replicaCounts.processors | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-processor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-processor
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: ['divvycloudworker','-t','processor','-n']
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret           
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
