# Default values for divvycloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
    imageName: divvycloud/divvycloud
    tag: v18.4.21
    pullPolicy: IfNotPresent

replicaCounts:
  harvesters: 2
  interfaceservers: 2
  schedulers: 2
  processors: 2
  longharvesters: 2
  ondemands: 2


# STORAGE #
# Uncomment this section if you plan on using PVC.
# We will use your default PVC class.
#storage:
#  size: 30Gi


# REDIS CONFIG #
# Uncomment this to use an external redis queue.

#redis_host: dns.name.to.redis.host

# END OF REDIS CONFIG #

# DATABASE CONFIG #

# Uncomment this section if you want to use an exteranl database.
# Please ensure that both divvy and divvykeys shecmas exist and 
# that the user has permissions on both schemas
#database_host: dns.name.to.mysql.host
#database_port: 3306

# If you are using an external DB , please update the username and passwords
database_user: divvy
database_password: divvy123

# END OF DATABASE CONFIG #

## Comment the below section if you want to run without an ingress rule
#
ingress:
  enabled: false
#  path: /
#  hosts:
#    - crosskube.divvycloud.io
### Uncommend the following lines if you are using an Nginx controller
#  annotations: {
#     kubernetes.io/ingress.class: nginx,
#     kubernetes.aio/tls-acme: "true"
#     }


service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
