# Default values for divvycloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageName: divvycloud/divvycloud:latest
imagePullPolicy: Always

# DATABASE CONFIG #

# Uncomment this section if you want to use an exteranl database.
# Please ensure that both divvy and divvykeys shecmas exist and 
# that the user has permissions on both schemas

externalDb: False
databaseHost: mysql
databasePort: 3306
databaseUser: divvy
databasePassword: divvy

# STORAGE #
#  We will use a PVC for the MySQL db.
#  If your kubernetes cluster does not support PVC, please change pvcEnabled to false
pvcEnabled: true
storageSize: 30Gi

# END OF DATABASE CONFIG #


## INGRESS

## Comment the below section if you want to run without an ingress rule
#
ingress:
  enabled: false
#  path: /
#  hosts:
#    - crosskube.divvycloud.io
### Uncommend the following lines if you are using an Nginx controller
#  annotations: {
#     kubernetes.io/ingress.class: nginx,
#     kubernetes.aio/tls-acme: "true"
#     }

# END OF INGRESS #

# Use a GCP Internal Loadbalancer
internalLoadBalancer: false

# DivvyCloud starting scale
replicaCounts:
  harvesters: 2
  interfaceservers: 2
  schedulers: 2
  processors: 2
  longharvesters: 2
  ondemands: 2

