apiVersion: v1
kind: Service
metadata:
  name: {{ template "divvycloud.name" . }}-redis
  labels:
    app: {{ template "divvycloud.name" . }}-redis
    chart: {{ template "divvycloud.chart" . }}-redis
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: {{ template "divvycloud.name" . }}-redis
    release: {{ .Release.Name }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-redis
  release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-redis
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: redis
        name: {{ template "divvycloud.name" . }}-redis
        ports:
        - containerPort: 6379

