{{- $mysql_host := (printf "%s-mysql" (include "divvycloud.name" .)) -}}
{{- $redis_host := (printf "%s-redis" (include "divvycloud.name" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "divvycloud.name" . }}-secret
data:
  DIVVY_MYSQL_USER : {{ .Values.database_user | default "divvy" | b64enc }}
  DIVVY_MYSQL_HOST: {{ .Values.database_host | default $mysql_host | b64enc }}
  DIVVY_MYSQL_PASSWORD : {{ .Values.database_password | default "divvy" | b64enc }}
  DIVVY_SECURE_MYSQL_USER : {{ .Values.secure_database_user | default "divvy" | b64enc }}
  DIVVY_SECURE_MYSQL_PASSWORD : {{ .Values.secure_database_password | default "divvy" | b64enc }}
  DIVVY_SECURE_MYSQL_HOST: {{ .Values.database_secure_host | default $mysql_host | b64enc }}
  DIVVY_REDIS_HOST: {{ .Values.redis_host | default $redis_host  | b64enc }}







